const { GoogleSpreadsheet } = require('google-spreadsheet');
const config = require("../config");
const { JWT } = require('google-auth-library');
const fs = require('fs');

// const doc = new GoogleSpreadsheet(config.spreadsheet);
const creds = require("../other/googlekey.json");

module.exports.lookup = async function() {
    await lookup();
}
const tweets = [];

var lookup = async function() {
    const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: creds.client_email,
  key: creds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});
    const doc = new GoogleSpreadsheet(config.spreadsheet,serviceAccountAuth);
    // await doc.useServiceAccountAuth(creds);
    await doc.loadInfo();
    console.log(doc.title+" has been opened");
    // const info = await doc.getInfo();
    const sheet = doc.sheetsByTitle["Devs; post-Revival"];
    n=sheet.rowCount
    n=n
    console.log(n)
    //n=192
    i=2
    const load = 'A5:I'+n;
    await sheet.loadCells(load);
    console.log("sheet has opened" + load);
    console.log(sheet.title);
    //loop through rows
    for (i=5;i<=n;i++){
        const date = sheet.getCell(i-1, 0);
        const Author = sheet.getCell(i-1, 1);
        const LinkText = sheet.getCell(i-1, 2);
        let Link = null;
        if(LinkText.value!=null){
            Link = LinkText.hyperlink;
        }
        const tweet = sheet.getCell(i-1, 3);
        const importance = sheet.getCell(i-1, 5);
        const tags = sheet.getCell(i-1, 7);
        const notes = sheet.getCell(i-1, 8);
        if (date.value==null){
            break;
        }
        //reformat date to mm dd yyyy
        const d = new Date((date.value - (25567 + 2)) * 86400 * 1000);
        const formattedDate = (d.getMonth() + 1) + ' ' + d.getDate() + ' ' + d.getFullYear();
        if(Link!=null){
            console.log(formattedDate + " | " + Author.value + " | " + Link + " | " + tweet.value + " | " + importance.value + " | " + tags.value + " | " + notes.value);
            let summary = "'"+tweet.value+"' by "+Author.value;
            if(notes.value!=null){
                summary += "\n\n(" + notes.value + ")";
            }
            let tagsList = [];
            tagsList.push(Author.value);
            if(tags.value!=null){
                const splitTags = tags.value.split(",");
                for (let t of splitTags){
                    tagsList.push(t.trim());
                }
            }
            let sources = [];
            if(Link!=null){
                sources=[{
                    1:[
                        "tweet by "+Author.value,
                        Link
                    ]
                }];
                tweets.push({
                mainPlatform: "tweet",
                summary: LinkText.value,
                mainText: summary,
                date: formattedDate,
                tags: tagsList,
                sources: sources
            });
            }

        }
        
    }
    console.log(tweets.length + " tweets found");
    //export to 2025-3.json
    fs.writeFileSync('data/devs-post-revival.json', JSON.stringify(tweets, null, 2));


}